project_name: drone-cache
before:
  hooks:
    - make clean
    - make vendor
dist: target/dist
builds:
-
  goos:
    - darwin
    - linux
    - windows
    # github.com/mattn/go-ieproxy vendor/github.com/mattn/go-ieproxy/GetProxyFunc.go:10:9: undefined: proxyMiddleman
    # - openbsd
    # - freebsd
    # - netbsd
    # - dragonfly
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  env:
    - CGO_ENABLED=0
  flags:
    -tags netgo
  ldflags: >
    -s
    -w
    -X main.Version={{.Version}}
    -X main.Commit={{.ShortCommit}}
    -X main.Date={{.Date}}
  ignore:
    - goos: darwin
      goarch: 386
  hooks:
    # Ignores failures, this is just best effort. Alternative: find target/dist -name drone-cache -type f -exec upx {} +
    post: find target/dist -name drone-cache -type f -print0 | xargs -n 1 -0 upx
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt" # default
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}" # default
release:
  github:
    owner: meltwater
    name: drone-cache
  disable: true
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - drone-cache
    image_templates:
    - "meltwater/drone-cache:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.build-date={{.Date}}"
    - "--label=org.label-schema.vcs-ref={{.FullCommit}}"
    - "--label=org.label-schema.docker.dockerfile=Dockerfile"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
